### PR TITLE
Windows support: route IPC through ipc.py (TCP on Windows, AF_UNIX on POSIX)

### LINKED ISSUE #124: Windows support: 4 issues found during fresh install (AF_UNIX, /tmp paths, emoji encoding, Chrome 147 user-data-dir)
Tested on: Windows 11 Pro 26200, Chrome 147.0.7727.102, Python 3.14 (uv-managed)

Four issues hit during a fresh install on Windows. Fixes for all four are straightforward.
Note: websockets 16.0 + Chrome 147 CDP failure is already tracked in #106.

---

## 1. `socket.AF_UNIX` not available in uv-managed Python builds

All Python versions installed via `uv python install` on Windows lack
`socket.AF_UNIX`, even though Windows 10+ (build 17093+) supports it at the OS
level. The python-build-standalone distributions that uv uses are compiled
without it.

**Error:**
```
AttributeError: module 'socket' has no attribute 'AF_UNIX'
```

This crashes `daemon_alive()` immediately on startup before any connection
attempt. Same root cause kills `asyncio.start_unix_server` (not defined on
Windows either).

**Fix:** TCP fallback on Windows. In `admin.py`/`daemon.py`/`helpers.py`,
detect `platform.system() == "Windows"` and use `asyncio.start_server` on
`127.0.0.1:0`, writing the assigned port to a `.port` file alongside the
existing `.pid` file.

---

## 2. Hardcoded `/tmp/` paths don't exist on Windows

`daemon.py` and `helpers.py` hardcode `/tmp/bu-{NAME}.sock` etc.
`/tmp/` doesn't exist on Windows — `tempfile.gettempdir()` returns
`C:\Users\<user>\AppData\Local\Temp`.

**Fix:** Replace the `/tmp/` prefix with `tempfile.gettempdir()` in both files.

---

## 3. Chrome 147 silently refuses `--remote-debugging-port` with the default user data directory

When Chrome is launched with `--remote-debugging-port=9222` but without an
explicit `--user-data-dir`, Chrome 147 prints the following to stderr and never
creates `DevToolsActivePort` or opens any TCP port:

```
DevTools remote debugging requires a non-default data directory.
Specify this using --user-data-dir.
```

Chrome starts and opens normally — there is no visible error to the user, and
no hint in the daemon's error output either. The daemon just times out after
60 s with "DevToolsActivePort not found".

**Workaround:** always launch Chrome with an explicit `--user-data-dir` pointing
to a non-default path, e.g.:

```
chrome.exe --remote-debugging-port=0 --user-data-dir="%LOCALAPPDATA%\Google\Chrome\HarnessProfile"
```

This should be documented prominently in `install.md` and ideally detected in
`get_ws_url()` so the error message is actionable instead of generic.

Additional wrinkle on Windows: if `--user-data-dir` contains spaces (common
for user home dirs like `C:\Users\Armin Seltz\...`), PowerShell's
`Start-Process -ArgumentList` silently truncates the path at the first space.
The launch script / docs should use Python `subprocess.Popen([...])` or ensure
the argument is properly quoted.

---

## 4. `UnicodeEncodeError` when printing tab titles on Windows

`_mark_tab()` prepends 🟢 to the browser tab title. On Windows, the default
stdout encoding is cp1252, which can't encode that character. Any `print()` of
`page_info()["title"]` after tab activation raises:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f7e2'
```

**Fix:** Add to `run.py` startup:

```python
if hasattr(sys.stdout, "reconfigure"):
    try: sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception: pass
```

Or set `PYTHONUTF8=1` in the environment before invoking `browser-harness`.

### PR DESCRIPTION
**Pull request by Alezander9**
## Summary

The harness was Linux/macOS-only because daemon IPC hardcoded `AF_UNIX` sockets at `/tmp/bu-*.sock` paths and `asyncio.start_unix_server`. On Windows none of these work, and `uv`-managed Python (python-build-standalone) ships without `socket.AF_UNIX` entirely.

This PR centralizes the platform fork in a new `ipc.py`:

- **POSIX**: `AF_UNIX` socket at `<tempdir>/bu-<NAME>.sock` (chmod 0600). Logically equivalent to the prior code, just relocated through one helper.
- **Windows**: TCP loopback on `127.0.0.1:<ephemeral port>`, with the chosen port written to `<tempdir>/bu-<NAME>.port` so clients can find the daemon. Uses stdlib `asyncio.start_server` — no third-party deps, no obscure APIs.

All log/pid/port files now sit under `tempfile.gettempdir()` so they land in `/tmp` on Linux, `$TMPDIR` on macOS, `%TEMP%` on Windows. `helpers.screenshot()` default path moved similarly.

`subprocess` detach uses `start_new_session=True` on POSIX and `DETACHED_PROCESS|CREATE_NEW_PROCESS_GROUP` on Windows via `ipc.spawn_kwargs()`.

`run.py` reconfigures stdout to UTF-8 on Windows so `print(page_info())` doesn't `UnicodeEncodeError` on the 🟢 marker helpers prepend to tab titles.

## Closes / addresses

- Closes #124 item 1 (`AF_UNIX` not available in uv-managed Python)
- Closes #124 item 2 (hardcoded `/tmp` paths)
- Closes #124 item 4 (`UnicodeEncodeError` on cp1252 stdout)
- Item 3 (Chrome 147 user-data-dir) is a separate concern, not addressed here

Thanks to @seltzdesign for the detailed Windows triage in #124. The TCP-on-Windows direction was inspired by their proposal.

## Why TCP on Windows, not named pipes

I prototyped named pipes first (`asyncio.start_serving_pipe` + a custom `_PipeClient`) and verified it worked end-to-end, but it required:

- A custom `asyncio.Protocol` subclass adapting raw pipe transport to the `(reader, writer)` handler shape `asyncio.start_unix_server` provides automatically.
- Inheriting from `asyncio.streams.FlowControlMixin` to make `StreamWriter.drain()` work — that bug only surfaces under named pipes because so few people use the pipe API.
- A separate `_PipeClient` wrapping a binary file handle to emulate a socket interface for blocking clients.

TCP on Windows + AF_UNIX on POSIX is **simpler** (50 LoC of logic vs. 80), uses **only the most boring stdlib asyncio APIs**, and `connect()` returns a real `socket` on both platforms instead of a wrapper. The trade-off is a port allocation per daemon and a `.port` sidecar file; in exchange we drop ~60 lines of platform-specific glue.

## Verification

**Windows 11 Pro + Chrome 147 + uv-managed Python 3.12** — full end-to-end:

```powershell
> uv run python -c "from admin import ensure_daemon; ensure_daemon(); print('up')"
up
> uv run python -c "from helpers import goto, page_info, screenshot; import time; goto('https://example.com'); time.sleep(2); print(page_info()); print(screenshot())"
{'url': 'https://example.com/', 'title': '🟢 Example Domain', 'w': 2560, 'h': 1295, 'sx': 0, 'sy': 0, 'pw': 2560, 'ph': 1295}
C:\Users\alexa\AppData\Local\Temp\shot.png
> Get-Item $env:TEMP\shot.png | Select-Object Length

Length
------
 20352

> uv run python -c "from admin import restart_daemon; restart_daemon(); print('stopped')"
stopped
> Test-Path $env:TEMP\bu-default.pid
False
```

**POSIX path**: not yet tested in this branch, but is logically equivalent to the previous code (same `AF_UNIX` call, same `chmod 0600`, same socket-file semantics) routed through `ipc.py`'s POSIX branch. **One observable behavior change on macOS**: socket/log/pid/screenshot files now land in `$TMPDIR` (`/var/folders/...`) instead of `/tmp`. They all move together; any caller hardcoding `/tmp/bu-*` paths would need updating.

## Files changed

- `ipc.py` (new) — platform fork
- `daemon.py` — replace `/tmp/...` constants and `AF_UNIX` plumbing with `ipc.*` calls
- `admin.py` — same: `_paths`, `_log_tail`, `daemon_alive`, `restart_daemon`. Also swap `start_new_session=True` for `**ipc.spawn_kwargs()`
- `helpers.py` — `_send` socket → `ipc`, `screenshot()` default path → `tempfile.gettempdir()`
- `run.py` — Windows UTF-8 stdout reconfigure
- `pyproject.toml` — add `ipc` to `py-modules`
- `SKILL.md`, `interaction-skills/connection.md` — update `/tmp/bu-*` references to be cross-platform

### CODE REVIEW

**Comment by Alezander9** [comment]
Thanks @cubic-dev-ai. Addressed all four findings in b749f82:

- **daemon.py:1, SKILL.md:151** — docstring/diagram updated to say TCP loopback. Took the suggested wording.
- **daemon.py:209** — fixed the missed-serve-crash issue, but with a tighter shape than the suggestion. Race `serve_task` and `stop_task` via `asyncio.wait(FIRST_COMPLETED)`; if `serve_task` finishes first it must have raised (it never returns on success), so `await` it to surface the exception. `finally` cancels both unconditionally. Same correctness guarantee, less machinery, no early `done()` check needed because the wait covers both states.
- **ipc.py:45** — added `_check(name)` validating `^[A-Za-z0-9_-]{1,64}$`, called from every path builder (`log_path`/`pid_path`/`port_path`/`_sock_path`). Single point of validation, bad names raise `ValueError` early.

Re-tested name validation, serve-crash detection, and the normal shutdown path. End-to-end Windows + POSIX still pass.
