### ISSUE TITLE
Windows support: 4 issues found during fresh install (AF_UNIX, /tmp paths, emoji encoding, Chrome 147 user-data-dir)

### ISSUE THREAD

**Issue by seltzdesign** [browser-use/browser-harness#124]
Tested on: Windows 11 Pro 26200, Chrome 147.0.7727.102, Python 3.14 (uv-managed)

Four issues hit during a fresh install on Windows. Fixes for all four are straightforward.
Note: websockets 16.0 + Chrome 147 CDP failure is already tracked in #106.

---

## 1. `socket.AF_UNIX` not available in uv-managed Python builds

All Python versions installed via `uv python install` on Windows lack
`socket.AF_UNIX`, even though Windows 10+ (build 17093+) supports it at the OS
level. The python-build-standalone distributions that uv uses are compiled
without it.

**Error:**
```
AttributeError: module 'socket' has no attribute 'AF_UNIX'
```

This crashes `daemon_alive()` immediately on startup before any connection
attempt. Same root cause kills `asyncio.start_unix_server` (not defined on
Windows either).

**Fix:** TCP fallback on Windows. In `admin.py`/`daemon.py`/`helpers.py`,
detect `platform.system() == "Windows"` and use `asyncio.start_server` on
`127.0.0.1:0`, writing the assigned port to a `.port` file alongside the
existing `.pid` file.

---

## 2. Hardcoded `/tmp/` paths don't exist on Windows

`daemon.py` and `helpers.py` hardcode `/tmp/bu-{NAME}.sock` etc.
`/tmp/` doesn't exist on Windows — `tempfile.gettempdir()` returns
`C:\Users\<user>\AppData\Local\Temp`.

**Fix:** Replace the `/tmp/` prefix with `tempfile.gettempdir()` in both files.

---

## 3. Chrome 147 silently refuses `--remote-debugging-port` with the default user data directory

When Chrome is launched with `--remote-debugging-port=9222` but without an
explicit `--user-data-dir`, Chrome 147 prints the following to stderr and never
creates `DevToolsActivePort` or opens any TCP port:

```
DevTools remote debugging requires a non-default data directory.
Specify this using --user-data-dir.
```

Chrome starts and opens normally — there is no visible error to the user, and
no hint in the daemon's error output either. The daemon just times out after
60 s with "DevToolsActivePort not found".

**Workaround:** always launch Chrome with an explicit `--user-data-dir` pointing
to a non-default path, e.g.:

```
chrome.exe --remote-debugging-port=0 --user-data-dir="%LOCALAPPDATA%\Google\Chrome\HarnessProfile"
```

This should be documented prominently in `install.md` and ideally detected in
`get_ws_url()` so the error message is actionable instead of generic.

Additional wrinkle on Windows: if `--user-data-dir` contains spaces (common
for user home dirs like `C:\Users\Armin Seltz\...`), PowerShell's
`Start-Process -ArgumentList` silently truncates the path at the first space.
The launch script / docs should use Python `subprocess.Popen([...])` or ensure
the argument is properly quoted.

---

## 4. `UnicodeEncodeError` when printing tab titles on Windows

`_mark_tab()` prepends 🟢 to the browser tab title. On Windows, the default
stdout encoding is cp1252, which can't encode that character. Any `print()` of
`page_info()["title"]` after tab activation raises:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f7e2'
```

**Fix:** Add to `run.py` startup:

```python
if hasattr(sys.stdout, "reconfigure"):
    try: sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception: pass
```

Or set `PYTHONUTF8=1` in the environment before invoking `browser-harness`.

**Comment by ignaciocebral** [comment]
Verified on April 20, 2026 on native Windows 10 Enterprise build 26200, Chrome 147.0.7727.56, Python 3.12.9, and uv 0.11.7.

I did a fresh install from current `main` in a native Windows checkout and connected the harness to an already-running real Chrome profile.

Exact failures I hit locally:

1. Immediate crash in `admin.daemon_alive()` before any Chrome attach attempt:

```text
AttributeError: module 'socket' has no attribute 'AF_UNIX'
```

2. Hardcoded `/tmp` assumptions were wrong on Windows for daemon artifacts and the default screenshot path.

3. After enabling `chrome://inspect/#remote-debugging` on the normal Chrome profile, the harness attached successfully, but `print(page_info())` then raised a Windows console encoding failure because `_mark_tab()` prepends `🟢` to the title and stdout was still cp1252:

```text
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f7e2'
```

Local fix I verified end-to-end:

- TCP loopback fallback for the local daemon transport on Windows
- tempdir-based daemon/log/pid/screenshot paths instead of hardcoded `/tmp`
- `run.py` forcing UTF-8 on stdout/stderr
- packaging update so the new transport module is installed
- a small regression test to confirm `admin.daemon_alive()` no longer crashes on Windows

With that patch applied, `browser-harness` attached to the existing logged-in Chrome session and opened `https://github.com/browser-use/browser-harness` in the real browser successfully.

One useful distinction from the Chrome 147 `--user-data-dir` case in the issue body: I did not need to launch Chrome with `--remote-debugging-port` at all. The real-browser attach flow worked after opening `chrome://inspect/#remote-debugging` in the normal profile, ticking the checkbox once, and clicking `Allow` if prompted. After that, `DevToolsActivePort` appeared and the harness connected normally.

I am not opening another upstream PR for this exact patch because it overlaps heavily with #100, #104, #110, and #122. I did push my exact reproduction/verification branch to my fork for reference: `ignaciocebral/browser-harness` branch `codex/windows-local-transport-verify`.

**Comment by SamuelMiller** [comment]
Some here. Deepwiki reported:

 `browser-harness` is primarily designed for Unix-like systems (macOS/Linux) and relies on Unix domain sockets (`AF_UNIX`) for its core communication between the daemon and the harness scripts [1](#0-0) [2](#0-1) [3](#0-2) .

## Windows Compatibility Status

**Native Windows is not supported** due to the fundamental reliance on Unix domain sockets. The architecture uses a local socket file (e.g., `/tmp/bu-default.sock`) as the communication bridge between `run.py` and `daemon.py` [4](#0-3) .

While the codebase does include some Windows-specific paths and platform detection [5](#0-4) [6](#0-5) , the core socket communication mechanism cannot work on standard Windows Python installations.

## Windows Solutions

### Option 1: Remote Browsers (Recommended)
Use the built-in remote browser feature, which works on any platform including Windows:

```bash
browser-harness <<'PY'
start_remote_daemon("work")
new_tab("https://example.com")
print(page_info())
PY
```

This provisions a cloud browser and connects via WebSocket instead of Unix sockets [7](#0-6) .

### Option 2: WSL
Install Windows Subsystem for Linux and run browser-harness within the Linux environment.

### Option 3: Alternative Architecture
The project would need significant architectural changes to support Windows natively, likely replacing Unix sockets with TCP sockets or named pipes.

## Notes

The remote browser approach is actually the intended solution for headless servers and non-Unix platforms, providing the same functionality without the local socket requirement [8](#0-7) .

Wiki pages you might want to explore:
- [Architecture & Core Components (browser-use/browser-harness)](/wiki/browser-use/browser-harness#2)
- [Glossary (browser-use/browser-harness)](/wiki/browser-use/browser-harness#5)

### Citations

**File:** daemon.py (L1-1)
```python
"""CDP WS holder + Unix socket relay. One daemon per BU_NAME."""
```

**File:** daemon.py (L24-24)
```python
SOCK = f"/tmp/bu-{NAME}.sock"
```

**File:** daemon.py (L38-42)
```python
    Path.home() / "AppData/Local/Google/Chrome/User Data",
    Path.home() / "AppData/Local/Microsoft/Edge/User Data",
    Path.home() / "AppData/Local/Microsoft/Edge Beta/User Data",
    Path.home() / "AppData/Local/Microsoft/Edge Dev/User Data",
    Path.home() / "AppData/Local/Microsoft/Edge SxS/User Data",
```

**File:** daemon.py (L208-210)
```python
    server = await asyncio.start_unix_server(handler, path=SOCK)
    os.chmod(SOCK, 0o600)
    log(f"listening on {SOCK} (name={NAME}, remote={REMOTE_ID or 'local'})")
```

**File:** helpers.py (L26-28)
```python
def _send(req):
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.connect(SOCK)
```

**File:** admin.py (L152-154)
```python
    system = platform.system()
    if system in ("Darwin", "Windows"):
        return True
```

**File:** admin.py (L215-240)
```python
def start_remote_daemon(name="remote", profileName=None, **create_kwargs):
    """Provision a Browser Use cloud browser and start a daemon attached to it.

    kwargs forwarded to `POST /browsers` (camelCase):
      profileId        — cloud profile UUID; start already-logged-in. Default: none (clean browser).
      profileName      — cloud profile name; resolved client-side to profileId via list_cloud_profiles().
      proxyCountryCode — ISO2 country code (default "us"); pass None to disable the BU proxy.
      timeout          — minutes, 1..240.
      customProxy      — {host, port, username, password, ignoreCertErrors}.
      browserScreenWidth / browserScreenHeight, allowResizing, enableRecording.

    Returns the full browser dict including `liveUrl`. Prints the liveUrl and
    auto-opens it locally when a GUI is detected, so the user can watch along."""
    if daemon_alive(name):
        raise RuntimeError(f"daemon {name!r} already alive -- restart_daemon({name!r}) first")
    if profileName:
        if "profileId" in create_kwargs:
            raise RuntimeError("pass profileName OR profileId, not both")
        create_kwargs["profileId"] = _resolve_profile_name(profileName)
    browser = _browser_use("/browsers", "POST", create_kwargs)
    ensure_daemon(
        name=name,
        env={"BU_CDP_WS": _cdp_ws_from_url(browser["cdpUrl"]), "BU_BROWSER_ID": browser["id"]},
    )
    _show_live_url(browser.get("liveUrl"))
    return browser
```

**File:** SKILL.md (L43-62)
```markdown
### Remote browsers

Use remote for **parallel sub-agents** (each gets its own isolated browser via a distinct `BU_NAME`) or on a headless server. `BROWSER_USE_API_KEY` must be set. `start_remote_daemon`, `list_cloud_profiles`, `list_local_profiles`, `sync_local_profile` are pre-imported.

```bash
browser-harness <<'PY'
start_remote_daemon("work")                               # default — clean browser, no profile
# start_remote_daemon("work", profileName="my-work")      # reuse a cloud profile (already logged in)
# start_remote_daemon("work", profileId="<uuid>")         # same, but by UUID
# start_remote_daemon("work", proxyCountryCode="de", timeout=120)   # DE proxy, 2-hour timeout
# start_remote_daemon("work", proxyCountryCode=None)      # disable the Browser Use proxy
PY

BU_NAME=work browser-harness <<'PY'
new_tab("https://example.com")
print(page_info())
PY
```

`start_remote_daemon` prints `liveUrl` and auto-opens it in the local browser (if a GUI is detected) so the user can watch along. Headless servers print only — share the URL with the user. The daemon `PATCH`es the cloud browser to `stop` on shutdown, which persists profile state. Running remote daemons bill until timeout.
```

**Comment by seltzdesign** [comment]
Fair enough. Fwiw, its working fine on Windows for me now with the fixes outlined in the 4 issues and I am happily using Browser Harness with Claude Code from VSCode on Windows 11. Seems like there are PRs for at least some of the issues now, so I'm going to close the issue.

**Comment by Alezander9** [comment]
Thanks @seltzdesign for the detailed triage. Opened #225 which addresses items 1, 2, and 4:

- **Item 1 (AF_UNIX missing in uv-Python)** — gated all `AF_UNIX` references behind `if not IS_WINDOWS` and added a TCP loopback path on Windows (your suggestion — agreed it's the right shape).
- **Item 2 (`/tmp` paths)** — all log/pid/port files now use `tempfile.gettempdir()`.
- **Item 4 (UnicodeEncodeError on cp1252)** — `run.py` reconfigures stdout to UTF-8 with `errors='replace'` on Windows.

Item 3 (Chrome 147 user-data-dir) is a separate concern — happy to take a follow-up PR on it if you want to send one, since you have the repro setup.

Verified end-to-end on Windows 11 with Chrome 147 + uv-managed Python 3.12 — full `ensure_daemon` → `goto` → `page_info` → `screenshot` → `restart_daemon` flow works. POSIX path is logically equivalent to the previous code (same AF_UNIX socket, chmod 0600), just routed through one helper module.

**Comment by Alezander9** [comment]
Is Chrome 147 user data dir still a issue today?
